permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 陈宗良
  email: nutchen@gmail.com
  link: https://chenzongliang.github.io
  github: https://chenzongliang.github.io

# 站点信息
title: 陈宗良的博客 
description: 陈宗良的博客 
url: https://chenzongliang.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: https://github.com/chenzongliang/chenzongliang.github.com/blob/master/images/head.jpg
favicon: https://github.com/chenzongliang/chenzongliang.github.com/blob/master/images/head.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: https://chenzongliang.github.io

# disqus 设置
disqus:
  shortname: chenzongliang-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
