auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: zongliangchen
url: http://chenzongliang.github.io/
feed: /atom.xml
author_info: <a href="http://chenzongliang.github.io/">chenzongliang</a>
